# Generated by Django 4.1 on 2022-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('emotions', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('no_distracted', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
