# Generated by Django 4.1 on 2022-11-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_branch_alter_profile_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='erp',
        ),
    ]
