# Generated by Django 4.1 on 2022-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='audio_store',
            table='Time_store',
        ),
    ]
